name: geoclimate-fetcher
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8,<3.13
  - pip>=21.0
  - earthengine-api>=0.1.380
  - geemap=0.26.0
  - ipyleaflet=0.17.2
  - ipywidgets=8.0.6
  - ipython=8.12.0
  - jupyter-core>=4.11.1
  - pandas
  - xarray
  - netcdf4
  - scipy
  - tqdm
  - geopandas
  - rasterio
  - jupyter>=1.0.0
  - folium>=0.14.0
  - pip:
    - jupyter-leaflet==0.19.0
    - rapidfuzz
    - rich
    - rio-cogeo
    - streamlit>=1.25.0
    - streamlit-folium>=0.15.0 